### ISSUE TITLE
Wo werden die "dynamischen Inhalte" hinzugefügt.

### ISSUE THREAD

**Issue by 205er** [ffbsee/gateway-page#1]
Moin D01JLR,

an welcher Stelle werden die dynamischen Inhalte hinzugefügt? Z.B. der GW-Name (`<h1>gw02.ffbsee.de</h1>`) und die zugehörigen CSS-Style-Angaben?
Auf https://gw02.ffbsee.de/ stimmt das HTML-file nicht mit dem hier abgelegten file überein.

Grüße

**Comment by DO1JLR** [comment]
Moin Falko

Ich bin noch am üben wie man mit submodules gut arbeitet. Daher war das offenbar doch nicht gepushed. Aufjedenfall ist die index.html nur ein Template dür das [ansible](https://github.com/ffbsee/ansible/tree/master/templates).
Und daher fügt Lektor basierend auf den variablen im Template dort infos ein!
